apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yaml
  - pvc.yaml
  - mysql-deploy.yaml
  - mysql-service.yaml
  - java-springboot-service.yaml
  - springboot-deploy.yaml
  - react-event-deploy.yaml
  - react-event-service.yaml
